In [2]:
import numpy as np
list_ = [ '1' , '2' , '3' , '4' , '5']
array_list = np.array(object = list_)

In [3]:
print("Data type of list_:", type(list_))
print("Data type of array_list:", type(array_list))


Data type of list_: <class 'list'>
Data type of array_list: <class 'numpy.ndarray'>


In [4]:
# For the 'list_' variable
for element in list_:
    print(f"Data type of element {element}: {type(element)}")

# For the 'array_list' variable
for element in array_list:
    print(f"Data type of element {element}: {type(element)}")


Data type of element 1: <class 'str'>
Data type of element 2: <class 'str'>
Data type of element 3: <class 'str'>
Data type of element 4: <class 'str'>
Data type of element 5: <class 'str'>
Data type of element 1: <class 'numpy.str_'>
Data type of element 2: <class 'numpy.str_'>
Data type of element 3: <class 'numpy.str_'>
Data type of element 4: <class 'numpy.str_'>
Data type of element 5: <class 'numpy.str_'>


In [5]:
array_list = np.array(object=list_, dtype=int)


In [6]:
# Data types of elements in the original 'list_'
for element in list_:
    print(f"Data type of element {element} in list_: {type(element)}")

# Data types of elements in the modified 'array_list'
for element in array_list:
    print(f"Data type of element {element} in array_list: {type(element)}")


Data type of element 1 in list_: <class 'str'>
Data type of element 2 in list_: <class 'str'>
Data type of element 3 in list_: <class 'str'>
Data type of element 4 in list_: <class 'str'>
Data type of element 5 in list_: <class 'str'>
Data type of element 1 in array_list: <class 'numpy.int64'>
Data type of element 2 in array_list: <class 'numpy.int64'>
Data type of element 3 in array_list: <class 'numpy.int64'>
Data type of element 4 in array_list: <class 'numpy.int64'>
Data type of element 5 in array_list: <class 'numpy.int64'>


In [7]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [8]:
# (i) Shape of num_array
shape = num_array.shape
print("Shape of num_array:", shape)

# (ii) Size of num_array
size = num_array.size
print("Size of num_array:", size)


Shape of num_array: (2, 3)
Size of num_array: 6


In [9]:
zero_matrix = np.zeros((3, 3))
print("3x3 Zero Matrix:")
print(zero_matrix)


3x3 Zero Matrix:
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
